# Generated by Django 3.1.2 on 2020-11-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmodel',
            old_name='images',
            new_name='snsimage',
        ),
    ]
